desc 'Precompile yar assetz'
task 'assets:precompile' do
  sh "mkdir -p #{File.expand_path('../public/assets', __FILE__)}"
  sh "touch #{File.expand_path('../public/assets/compiled_asset', __FILE__)}"
  sh 'touch precompiled'
end

